name: Rust_CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
    - name: Build
      run: make rust_build
    - name: Run
      run: make rust_run
    - name: Test
      run: make rust_test
    - name: Clean
      run: make rust_clean
    - name: Format
      run: make rust_format
    - name: Lint
      run: make rust_lint
    